# Generated by Django 4.0.4 on 2023-11-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('place', models.CharField(default='', max_length=500, verbose_name='Место хранения')),
                ('last_update_date', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
            ],
            options={
                'verbose_name': 'Посуда',
                'verbose_name_plural': 'Лабораторная посуда',
            },
        ),
    ]
