# Generated by Django 4.0.4 on 2023-09-29 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_clientsystem_secret_clientsystem_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsystem',
            name='is_assistant',
            field=models.BooleanField(default=False, verbose_name='Лаборант'),
        ),
    ]
