# Generated by Django 4.2.11 on 2024-06-03 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0002_items_additional_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания эксперимента')),
                ('is_done', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('status', models.CharField(default='В обработке', max_length=50, verbose_name='Статус эксперимента')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
                'db_table': 'work',
            },
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата выполнения эксперимента эксперимента')),
                ('results', models.FileField(blank=True, null=True, upload_to='works_results', verbose_name='Результаты эксперимента')),
                ('item', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='goods.items', verbose_name='Предмет')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.work', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Выполненная работа',
                'verbose_name_plural': 'Выполненные работы',
                'db_table': 'work_item',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
