# Generated by Django 4.0.4 on 2023-11-16 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_clientsystem_is_assistant'),
        ('research', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='research',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='works', to='research.research', verbose_name='Исследование'),
        ),
        migrations.AddField(
            model_name='work',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='clients.clientsystem', verbose_name='Студент'),
        ),
        migrations.AddField(
            model_name='value',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_fields', to='inventory.extrafields', verbose_name='Значение'),
        ),
        migrations.AddField(
            model_name='value',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.result', verbose_name='Результат'),
        ),
        migrations.AddField(
            model_name='extrafields',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_fields', to='inventory.equipment', verbose_name='Оборудование'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='inventory.work', verbose_name='Работа'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='laboratory_assistant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratory_assistant', to='clients.clientsystem', verbose_name='Ответственный за оборудование'),
        ),
        migrations.AddField(
            model_name='drymethod',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dry_methods', to='inventory.equipment', verbose_name='Оборудование'),
        ),
    ]
