# Generated by Django 4.2.11 on 2024-06-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='additional_image',
            field=models.ImageField(blank=True, null=True, upload_to='store_additional_images', verbose_name='Изображение'),
        ),
    ]
