# Generated by Django 4.2.11 on 2024-06-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_items_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='working_type',
            field=models.IntegerField(blank=True, choices=[(1, 'sks'), (2, 'example')], null=True, verbose_name='Тип работы'),
        ),
        migrations.AlterField(
            model_name='items',
            name='units',
            field=models.IntegerField(blank=True, choices=[(1, 'mg'), (2, 'g'), (3, 'kg'), (4, 'ml'), (5, 'l')], null=True, verbose_name='Единицы измерения'),
        ),
    ]
