# Generated by Django 4.0.4 on 2023-10-02 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_clientsystem_is_assistant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=100, verbose_name='Тема')),
                ('discription', models.TextField(max_length=200, verbose_name='Описание')),
                ('date_create', models.DateField()),
                ('date_processed', models.DateField()),
                ('result', models.CharField(max_length=100, verbose_name='Результат')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_applicant', to='clients.clientsystem', verbose_name='Заявитель')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_responsible', to='clients.clientsystem', verbose_name='Ответсвенный')),
            ],
            options={
                'verbose_name': 'Обращения',
                'verbose_name_plural': 'Обращение',
            },
        ),
    ]
