# Generated by Django 4.0.4 on 2023-12-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date_create',
            field=models.DateField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='request',
            name='date_processed',
            field=models.DateField(verbose_name='Дата обработки'),
        ),
    ]
