# Generated by Django 4.0.4 on 2024-03-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_alter_request_date_create_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='discription',
        ),
        migrations.AddField(
            model_name='request',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='result',
            field=models.TextField(verbose_name='Результат'),
        ),
    ]
