# Generated by Django 4.0.4 on 2023-11-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_clientsystem_is_assistant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('student', models.ManyToManyField(related_name='student_research', to='clients.clientsystem', verbose_name='Студент')),
                ('teacher', models.ManyToManyField(related_name='teacher_research', to='clients.clientsystem', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Исследование студента',
                'verbose_name_plural': 'Исследование студента',
            },
        ),
    ]
