# Generated by Django 4.0.4 on 2023-11-16 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_clientsystem_is_assistant'),
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_works', to='clients.clientsystem', verbose_name='Студент')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='inventory.work', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Лабораторная работа студента',
                'verbose_name_plural': 'Лабораторные работы студента',
            },
        ),
        migrations.CreateModel(
            name='StudentWorkReagents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken', models.BooleanField(default=False)),
                ('real_quantity', models.FloatField(blank=True, null=True, verbose_name='Фактически взято')),
                ('reagent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.workreagents', verbose_name='Реагент')),
                ('student_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reagents', to='student.studentwork', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Реактивы студента',
                'verbose_name_plural': 'Реактивы студента',
            },
        ),
    ]
