# Generated by Django 4.2.11 on 2024-06-04 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_remove_workitem_results_work_additional_files_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='workitem',
            managers=[
            ],
        ),
    ]
