# Generated by Django 4.2.11 on 2024-06-05 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0007_alter_work_status_experiment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='status',
        ),
    ]
