# Generated by Django 4.2.11 on 2024-06-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0008_remove_work_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата бронирования'),
        ),
    ]
