# Generated by Django 4.2.11 on 2024-06-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0009_workitem_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='units',
            field=models.IntegerField(blank=True, choices=[(1, 'mg'), (2, 'g'), (3, 'kg'), (4, 'ml'), (5, 'l')], null=True, verbose_name='Единицы измерения'),
        ),
    ]
