# Generated by Django 4.2.11 on 2024-06-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_items_additional_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='units',
            field=models.IntegerField(blank=True, choices=[(1, 'mg'), (2, 'g'), (3, 'kg'), (4, 'ml'), (5, 'l'), (6, 'SKS')], null=True, verbose_name='Единицы измерения'),
        ),
    ]
