# Generated by Django 4.2.11 on 2024-06-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_items_working_type_alter_items_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Дата бронирования'),
        ),
    ]
