# Generated by Django 4.2.11 on 2024-06-05 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_items_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='date',
        ),
    ]
